#!/usr/bin/env python3
"""
Build LICENSE_CODE regex from Consejo de Mallorca census signatures (no filter).

Run the Consejo spider without the group filter to get all signature formats
(ETV/, VT/, TI/, ETVPL/, ET/, etc.). Crawl enough pages to get a representative
set of formats (e.g. several dozen pages), then run this script on the output:

  scrapy crawl consejo_mallorca -o data/consejo_all_signatures.jsonl

  python scripts/build_license_patterns.py data/consejo_all_signatures.jsonl

Or: cat data/consejo_all_signatures.jsonl | python scripts/build_license_patterns.py

Writes radarlicencias/data/license_patterns.py so the Airbnb spider can use the
canonical list of formats from the official registry.
"""

import argparse
import json
import re
import sys
from pathlib import Path

# Signature format: optional letters then optional separator (/ - space) then digits.
# Captures the prefix (e.g. ETV, VT, TI, ETVPL, ET).
SIGNATURE_PREFIX_RE = re.compile(r"^([A-Za-z]+)[/\-\s]*\d+.*$")


def extract_prefix(signature: str) -> str | None:
    """Get the license prefix from a signature, e.g. 'ETV/12345' -> 'ETV', 'VT/474' -> 'VT'."""
    if not signature or not signature.strip():
        return None
    s = signature.strip()
    # Match PREFIX + optional separator + digits
    m = re.match(r"^([A-Za-z]+)[/\-\s]*\d+", s)
    if m:
        return m.group(1).upper()
    return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Build LICENSE_CODE from Consejo JSONL signatures.")
    parser.add_argument(
        "input",
        nargs="?",
        default="-",
        help="Path to JSONL file (Consejo crawl output with 'signature' field). Default: stdin.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output path for license_patterns.py (default: radarlicencias/data/license_patterns.py)",
    )
    args = parser.parse_args()

    prefixes: set[str] = set()
    if args.input == "-":
        stream = sys.stdin
    else:
        stream = open(args.input, encoding="utf-8")

    try:
        for line in stream:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            sig = obj.get("signature") or obj.get("signatura")
            if not sig:
                continue
            pre = extract_prefix(sig)
            # Include all prefixes (including single-letter e.g. R/, D/) so we don't miss census formats.
            if pre:
                prefixes.add(pre)
    finally:
        if args.input != "-":
            stream.close()

    if not prefixes:
        print("No signatures found. Run Consejo spider first and pass its JSONL output.", file=sys.stderr)
        sys.exit(1)

    # Sort by length descending so longer prefixes (e.g. ETVPL) match before shorter (ETV, ET).
    sorted_prefixes = sorted(prefixes, key=lambda p: (-len(p), p))
    # Pattern per prefix: PREFIX + optional / - or space + digits (matches ETV/123, ETV-123, ETV 123, ETV123).
    pattern_parts = [p + r"[/\-\s]*\d+" for p in sorted_prefixes]
    pattern_str = "|".join(pattern_parts)

    out_dir = Path(__file__).resolve().parent.parent
    if args.output:
        out_path = Path(args.output)
    else:
        out_path = out_dir / "radarlicencias" / "data" / "license_patterns.py"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    content = f'''# Auto-generated by scripts/build_license_patterns.py from Consejo de Mallorca census (no filter).
# Regenerate after: scrapy crawl consejo_mallorca -o data/consejo_all_signatures.jsonl
# Then: python scripts/build_license_patterns.py data/consejo_all_signatures.jsonl

LICENSE_CODE = r"(?:{pattern_str})"
'''
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(prefixes)} prefix(es) to {out_path}: {sorted_prefixes}", file=sys.stderr)


if __name__ == "__main__":
    main()
